---
- hosts: localhost
  tasks:
  - include: docker-py.yaml
  - name: Create registry
    docker_container:
      name: registry
      state: started
      image: registry:latest
      published_ports: 5000:5000
      restart_policy: always
