---
- hosts: pls
  tasks:
  - include: docker.yaml
# CAMBIAR EN IMAGE LA IP POR LA DE LA VM DE CONTROL
  - name: Start some Centos containers
    docker_container:
      name: "centos_{{ item }}"
      image: 172.31.28.22:5000/centos
      interactive: true
      tty: true
    with_sequence: count=3

  - name: Start some Ubuntu containers
    docker_container:
      name: "ubuntu_{{ item }}"
      image: 172.31.28.22:5000/ubuntu
      interactive: true
      tty: true
    with_sequence: count=3
