---
- hosts: localhost
  tasks:
  - include: docker-py.yaml

  - name: Start some Centos containers
    docker_container:
      name: "centos"
      image: centos
      interactive: true
      tty: true
    with_sequence: count=3

  - name: Start some Ubuntu containers
    docker_container:
      name: "ubuntu"
      image: ubuntu
      interactive: true
      tty: true
    with_sequence: count=3
