---
- hosts: localhost
  become: true
  vars:
  - image: centos
  - number: 3
  tasks:

  - name: Install Python docker module
    pip:
      name: docker

  - name: "Start some {{ image }} containers"
    docker_container:
      name: "{{ image }}_{{ item }}"
      hostname: "{{ image }}_{{ item }}"
      image: "172.31.28.22:5000/{{ image }}"
      interactive: true
      tty: true
    with_sequence: "count={{ number }}"
