---
- hosts: localhost
  become: true
  vars:
  - image: centos
  - number: 3
  tasks:
  - name: Install python2 pip utility
    yum:
      name: python2-pip
      state: present

  - name: Install Python docker-py module
    pip:
      name: docker-py

  - name: "Start some {{ image }} containers"
    docker_container:
      name: "{{ image }}_{{ item }}"
      hostname: "{{ image }}_{{ item }}"
      image: "server1:5000/{{ image }}"
      interactive: true
      tty: true
    with_sequence: "count={{ number }}"
