all:
  children:
    aws_ec2:
      hosts:
        ip-172-31-0-107.us-west-2.compute.internal:
          ami_launch_index: 0
          ansible_host: 172.31.0.107
          architecture: x86_64
          block_device_mappings:
          - device_name: /dev/sda1
            ebs:
              attach_time: 2022-06-18 22:10:46+00:00
              delete_on_termination: true
              status: attached
              volume_id: vol-006dc6c7290ce7688
          capacity_reservation_specification:
            capacity_reservation_preference: open
          client_token: ''
          cpu_options:
            core_count: 1
            threads_per_core: 1
          ebs_optimized: false
          ena_support: true
          enclave_options:
            enabled: false
          hibernation_options:
            configured: false
          hypervisor: xen
          image_id: ami-08a69d5598384b3dd
          instance_id: i-0c3cf6ec8c88ef48e
          instance_type: t2.micro
          key_name: aho-key
          launch_time: 2022-06-18 22:57:16+00:00
          maintenance_options:
            auto_recovery: default
          metadata_options:
            http_endpoint: enabled
            http_protocol_ipv6: disabled
            http_put_response_hop_limit: 1
            http_tokens: optional
            instance_metadata_tags: enabled
            state: applied
          monitoring:
            state: disabled
          network_interfaces:
          - association:
              ip_owner_id: amazon
              public_dns_name: ec2-35-89-11-157.us-west-2.compute.amazonaws.com
              public_ip: 35.89.11.157
            attachment:
              attach_time: 2022-06-18 22:10:45+00:00
              attachment_id: eni-attach-0ae236ed503b88a8a
              delete_on_termination: true
              device_index: 0
              network_card_index: 0
              status: attached
            description: ''
            groups:
            - group_id: sg-036750bbc4146fd43
              group_name: default
            - group_id: sg-07306ddf70f8808d5
              group_name: acceso-ssh-ping-default
            interface_type: interface
            ipv6_addresses: []
            mac_address: 0a:d4:da:34:c4:d3
            network_interface_id: eni-01d480ea4e3938895
            owner_id: '482235079173'
            private_dns_name: ip-172-31-0-107.us-west-2.compute.internal
            private_ip_address: 172.31.0.107
            private_ip_addresses:
            - association:
                ip_owner_id: amazon
                public_dns_name: ec2-35-89-11-157.us-west-2.compute.amazonaws.com
                public_ip: 35.89.11.157
              primary: true
              private_dns_name: ip-172-31-0-107.us-west-2.compute.internal
              private_ip_address: 172.31.0.107
            source_dest_check: true
            status: in-use
            subnet_id: subnet-03b19b6557b8c051d
            vpc_id: vpc-099ea4a7ca75b1cc3
          owner_id: '482235079173'
          placement:
            availability_zone: us-west-2c
            group_name: ''
            region: us-west-2
            tenancy: default
          platform_details: Linux/UNIX
          private_dns_name: ip-172-31-0-107.us-west-2.compute.internal
          private_dns_name_options:
            enable_resource_name_dns_a_record: true
            enable_resource_name_dns_aaaa_record: false
            hostname_type: ip-name
          private_ip_address: 172.31.0.107
          product_codes:
          - product_code_id: cvugziknvmxgqna9noibqnnsy
            product_code_type: marketplace
          public_dns_name: ec2-35-89-11-157.us-west-2.compute.amazonaws.com
          public_ip_address: 35.89.11.157
          requester_id: ''
          reservation_id: r-05f40babb7097f6b3
          root_device_name: /dev/sda1
          root_device_type: ebs
          security_groups:
          - group_id: sg-036750bbc4146fd43
            group_name: default
          - group_id: sg-07306ddf70f8808d5
            group_name: acceso-ssh-ping-default
          source_dest_check: true
          state:
            code: 16
            name: running
          state_transition_reason: ''
          subnet_id: subnet-03b19b6557b8c051d
          tags:
            Group: pls
            Name: pls-vm2
          usage_operation: RunInstances
          usage_operation_update_time: 2022-06-18 22:10:45+00:00
          virtualization_type: hvm
          vpc_id: vpc-099ea4a7ca75b1cc3
        ip-172-31-2-176.us-west-2.compute.internal:
          ami_launch_index: 0
          ansible_host: 172.31.2.176
          architecture: x86_64
          block_device_mappings:
          - device_name: /dev/sda1
            ebs:
              attach_time: 2022-06-18 22:05:58+00:00
              delete_on_termination: true
              status: attached
              volume_id: vol-0fc172667c471cbf1
          capacity_reservation_specification:
            capacity_reservation_preference: open
          client_token: ''
          cpu_options:
            core_count: 1
            threads_per_core: 1
          ebs_optimized: false
          ena_support: true
          enclave_options:
            enabled: false
          hibernation_options:
            configured: false
          hypervisor: xen
          iam_instance_profile:
            arn: arn:aws:iam::482235079173:instance-profile/EC2Admin
            id: AIPAXAR3TLIC6EUGIYEXZ
          image_id: ami-08a69d5598384b3dd
          instance_id: i-05afb07c3a623be80
          instance_type: t2.micro
          key_name: pls-key-imported
          launch_time: 2022-06-18 22:05:57+00:00
          maintenance_options:
            auto_recovery: default
          metadata_options:
            http_endpoint: enabled
            http_protocol_ipv6: disabled
            http_put_response_hop_limit: 1
            http_tokens: optional
            instance_metadata_tags: disabled
            state: applied
          monitoring:
            state: disabled
          network_interfaces:
          - association:
              ip_owner_id: amazon
              public_dns_name: ec2-54-200-237-52.us-west-2.compute.amazonaws.com
              public_ip: 54.200.237.52
            attachment:
              attach_time: 2022-06-18 22:05:57+00:00
              attachment_id: eni-attach-039c369c77f2cb959
              delete_on_termination: true
              device_index: 0
              network_card_index: 0
              status: attached
            description: ''
            groups:
            - group_id: sg-036750bbc4146fd43
              group_name: default
            - group_id: sg-07306ddf70f8808d5
              group_name: acceso-ssh-ping-default
            interface_type: interface
            ipv6_addresses: []
            mac_address: 0a:e3:be:66:54:79
            network_interface_id: eni-0bbfe3edba729547a
            owner_id: '482235079173'
            private_dns_name: ip-172-31-2-176.us-west-2.compute.internal
            private_ip_address: 172.31.2.176
            private_ip_addresses:
            - association:
                ip_owner_id: amazon
                public_dns_name: ec2-54-200-237-52.us-west-2.compute.amazonaws.com
                public_ip: 54.200.237.52
              primary: true
              private_dns_name: ip-172-31-2-176.us-west-2.compute.internal
              private_ip_address: 172.31.2.176
            source_dest_check: true
            status: in-use
            subnet_id: subnet-03b19b6557b8c051d
            vpc_id: vpc-099ea4a7ca75b1cc3
          owner_id: '482235079173'
          placement:
            availability_zone: us-west-2c
            group_name: ''
            region: us-west-2
            tenancy: default
          platform_details: Linux/UNIX
          private_dns_name: ip-172-31-2-176.us-west-2.compute.internal
          private_dns_name_options:
            enable_resource_name_dns_a_record: true
            enable_resource_name_dns_aaaa_record: false
            hostname_type: ip-name
          private_ip_address: 172.31.2.176
          product_codes:
          - product_code_id: cvugziknvmxgqna9noibqnnsy
            product_code_type: marketplace
          public_dns_name: ec2-54-200-237-52.us-west-2.compute.amazonaws.com
          public_ip_address: 54.200.237.52
          requester_id: ''
          reservation_id: r-0eba7fad738fb3df2
          root_device_name: /dev/sda1
          root_device_type: ebs
          security_groups:
          - group_id: sg-036750bbc4146fd43
            group_name: default
          - group_id: sg-07306ddf70f8808d5
            group_name: acceso-ssh-ping-default
          source_dest_check: true
          state:
            code: 16
            name: running
          state_transition_reason: ''
          subnet_id: subnet-03b19b6557b8c051d
          tags:
            Group: pls
            Name: pls-vm1
          usage_operation: RunInstances
          usage_operation_update_time: 2022-06-18 22:05:57+00:00
          virtualization_type: hvm
          vpc_id: vpc-099ea4a7ca75b1cc3
    pls:
      hosts:
        ip-172-31-0-107.us-west-2.compute.internal: {}
        ip-172-31-2-176.us-west-2.compute.internal: {}
    ungrouped: {}
