---
- hosts: all
  tasks:

    - name: Instala Docker
      yum:
        name: docker
        state: present

    - name: Comprueba que existe el fichero de configuracion
      file:
        name: "/etc/docker"
        state: directory

    - name: Inserta el fichero de configuracion
      copy:
        dest: "/etc/docker/daemon.json"
        src: "daemon.json"

    - name: Habilita y Arranca el servicio
      systemd:
        name: docker
        enabled: yes
        state: restarted

    - name: pone los grupos secundarios del usuario centos
      user: 
        name: centos
        groups: dockerroot,adm,systemd-journal
