---
- hosts: ~web
  gather_facts: No
  tasks:
  - name: Drop by default
    iptables:
      chain: INPUT
      policy: DROP

  - name: Accept web
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 80
      jump: ACCEPT

  - name: Accept ICMP
    iptables:
      chain: INPUT
      protocol: icmp
      jump: ACCEPT
...
